theme: jekyll-theme-minimal
title: 2642.city document repository
description: Mirror of martonvasar.hu documents

show_downloads: "false"

defaults:
  - scope:
      path: "kepviselo-testuleti-jegyzokonyvek-2021"
    values:
      kepviselo-testuleti-jegyzokonyvek-2021: true
