theme: jekyll-theme-minimal
title: 2462.city document repository
description: Mirror of martonvasar.hu documents

defaults:
  - scope:
      path: "kepviselo-testuleti-jegyzokonyvek-2021"
    values:
      kepviselo-testuleti-jegyzokonyvek-2021: true
  - scope:
      path: "gazdasagi-bizottsag-jegyzokonyvek"
    values:
      gazdasagi-bizottsag-jegyzokonyvek: true

basepath: /documents
